# This is a basic workflow to help you get started with Actions

name: Angular-CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v4        
        with:
          persist-credentials: false # Añade esto
      # Setup nodeJS
      - name: Setup nodejs
        uses: actions/setup-node@v4.1.0
        with:
          node-version: "18"
      # Install dependencies
      - name: Install deps
        run: npm i
      # Build app for production
      - name: Build app bundle
        run: npm run build:prod
      # Deploy to Github pages
      - name: Deploy to Pages
        uses: peaceiris/actions-gh-pages@v3 # Cambiamos a otra action
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/sgtd-client/browser # Ajusta esta ruta según tu build
          force_orphan: true
